
# Virtual Machine (from fluidstack.io or lambda.com or any vm or on LAN)
:vm_ip: mkvgpu.local
# :vm_ip: 207.53.234.114

# VM username
:vm_username: makevoid  # custom user
# :vm_username: user    # (for fluidstack)
# :vm_username: ubuntu  # (user for lambda.com or AWS)
